services:
  db:
    image: postgres
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: billing-exercise # Simple creds for dev only
      POSTGRES_USER: billing-exercise
