// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build mock

package handler

import (
	"context"

	"gangsaur.com/billing-exercise/internal/repository/db/psql"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoanService creates a new instance of MockLoanService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoanService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoanService {
	mock := &MockLoanService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoanService is an autogenerated mock type for the LoanService type
type MockLoanService struct {
	mock.Mock
}

type MockLoanService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoanService) EXPECT() *MockLoanService_Expecter {
	return &MockLoanService_Expecter{mock: &_m.Mock}
}

// GetLoan provides a mock function for the type MockLoanService
func (_mock *MockLoanService) GetLoan(ctx context.Context, id int) (psql.Loan, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLoan")
	}

	var r0 psql.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (psql.Loan, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) psql.Loan); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(psql.Loan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoanService_GetLoan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoan'
type MockLoanService_GetLoan_Call struct {
	*mock.Call
}

// GetLoan is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockLoanService_Expecter) GetLoan(ctx interface{}, id interface{}) *MockLoanService_GetLoan_Call {
	return &MockLoanService_GetLoan_Call{Call: _e.mock.On("GetLoan", ctx, id)}
}

func (_c *MockLoanService_GetLoan_Call) Run(run func(ctx context.Context, id int)) *MockLoanService_GetLoan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoanService_GetLoan_Call) Return(loan psql.Loan, err error) *MockLoanService_GetLoan_Call {
	_c.Call.Return(loan, err)
	return _c
}

func (_c *MockLoanService_GetLoan_Call) RunAndReturn(run func(ctx context.Context, id int) (psql.Loan, error)) *MockLoanService_GetLoan_Call {
	_c.Call.Return(run)
	return _c
}

// GetLoanAndLoanPayments provides a mock function for the type MockLoanService
func (_mock *MockLoanService) GetLoanAndLoanPayments(ctx context.Context, id int) (psql.Loan, []psql.LoanPayment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLoanAndLoanPayments")
	}

	var r0 psql.Loan
	var r1 []psql.LoanPayment
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (psql.Loan, []psql.LoanPayment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) psql.Loan); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(psql.Loan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) []psql.LoanPayment); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]psql.LoanPayment)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = returnFunc(ctx, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockLoanService_GetLoanAndLoanPayments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoanAndLoanPayments'
type MockLoanService_GetLoanAndLoanPayments_Call struct {
	*mock.Call
}

// GetLoanAndLoanPayments is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockLoanService_Expecter) GetLoanAndLoanPayments(ctx interface{}, id interface{}) *MockLoanService_GetLoanAndLoanPayments_Call {
	return &MockLoanService_GetLoanAndLoanPayments_Call{Call: _e.mock.On("GetLoanAndLoanPayments", ctx, id)}
}

func (_c *MockLoanService_GetLoanAndLoanPayments_Call) Run(run func(ctx context.Context, id int)) *MockLoanService_GetLoanAndLoanPayments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLoanService_GetLoanAndLoanPayments_Call) Return(loan psql.Loan, loanPayments []psql.LoanPayment, err error) *MockLoanService_GetLoanAndLoanPayments_Call {
	_c.Call.Return(loan, loanPayments, err)
	return _c
}

func (_c *MockLoanService_GetLoanAndLoanPayments_Call) RunAndReturn(run func(ctx context.Context, id int) (psql.Loan, []psql.LoanPayment, error)) *MockLoanService_GetLoanAndLoanPayments_Call {
	_c.Call.Return(run)
	return _c
}

// PayLoan provides a mock function for the type MockLoanService
func (_mock *MockLoanService) PayLoan(ctx context.Context, id int, amount int) (psql.Loan, error) {
	ret := _mock.Called(ctx, id, amount)

	if len(ret) == 0 {
		panic("no return value specified for PayLoan")
	}

	var r0 psql.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (psql.Loan, error)); ok {
		return returnFunc(ctx, id, amount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) psql.Loan); ok {
		r0 = returnFunc(ctx, id, amount)
	} else {
		r0 = ret.Get(0).(psql.Loan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, id, amount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoanService_PayLoan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayLoan'
type MockLoanService_PayLoan_Call struct {
	*mock.Call
}

// PayLoan is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - amount int
func (_e *MockLoanService_Expecter) PayLoan(ctx interface{}, id interface{}, amount interface{}) *MockLoanService_PayLoan_Call {
	return &MockLoanService_PayLoan_Call{Call: _e.mock.On("PayLoan", ctx, id, amount)}
}

func (_c *MockLoanService_PayLoan_Call) Run(run func(ctx context.Context, id int, amount int)) *MockLoanService_PayLoan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLoanService_PayLoan_Call) Return(loan psql.Loan, err error) *MockLoanService_PayLoan_Call {
	_c.Call.Return(loan, err)
	return _c
}

func (_c *MockLoanService_PayLoan_Call) RunAndReturn(run func(ctx context.Context, id int, amount int) (psql.Loan, error)) *MockLoanService_PayLoan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUser(ctx context.Context, id int) (psql.User, bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 psql.User
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (psql.User, bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) psql.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(psql.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) bool); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = returnFunc(ctx, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserService_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserService_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockUserService_Expecter) GetUser(ctx interface{}, id interface{}) *MockUserService_GetUser_Call {
	return &MockUserService_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockUserService_GetUser_Call) Run(run func(ctx context.Context, id int)) *MockUserService_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetUser_Call) Return(user psql.User, b bool, err error) *MockUserService_GetUser_Call {
	_c.Call.Return(user, b, err)
	return _c
}

func (_c *MockUserService_GetUser_Call) RunAndReturn(run func(ctx context.Context, id int) (psql.User, bool, error)) *MockUserService_GetUser_Call {
	_c.Call.Return(run)
	return _c
}
