// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build mock

package service

import (
	"context"
	"time"

	"gangsaur.com/billing-exercise/internal/repository/db/psql"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// GetLoan provides a mock function for the type MockStore
func (_mock *MockStore) GetLoan(ctx context.Context, id int) (psql.Loan, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLoan")
	}

	var r0 psql.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (psql.Loan, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) psql.Loan); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(psql.Loan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetLoan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoan'
type MockStore_GetLoan_Call struct {
	*mock.Call
}

// GetLoan is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockStore_Expecter) GetLoan(ctx interface{}, id interface{}) *MockStore_GetLoan_Call {
	return &MockStore_GetLoan_Call{Call: _e.mock.On("GetLoan", ctx, id)}
}

func (_c *MockStore_GetLoan_Call) Run(run func(ctx context.Context, id int)) *MockStore_GetLoan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetLoan_Call) Return(loan psql.Loan, err error) *MockStore_GetLoan_Call {
	_c.Call.Return(loan, err)
	return _c
}

func (_c *MockStore_GetLoan_Call) RunAndReturn(run func(ctx context.Context, id int) (psql.Loan, error)) *MockStore_GetLoan_Call {
	_c.Call.Return(run)
	return _c
}

// GetLoanByUserIdAndStatus provides a mock function for the type MockStore
func (_mock *MockStore) GetLoanByUserIdAndStatus(ctx context.Context, userId int, status int) ([]psql.Loan, error) {
	ret := _mock.Called(ctx, userId, status)

	if len(ret) == 0 {
		panic("no return value specified for GetLoanByUserIdAndStatus")
	}

	var r0 []psql.Loan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]psql.Loan, error)); ok {
		return returnFunc(ctx, userId, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []psql.Loan); ok {
		r0 = returnFunc(ctx, userId, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]psql.Loan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, userId, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetLoanByUserIdAndStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoanByUserIdAndStatus'
type MockStore_GetLoanByUserIdAndStatus_Call struct {
	*mock.Call
}

// GetLoanByUserIdAndStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int
//   - status int
func (_e *MockStore_Expecter) GetLoanByUserIdAndStatus(ctx interface{}, userId interface{}, status interface{}) *MockStore_GetLoanByUserIdAndStatus_Call {
	return &MockStore_GetLoanByUserIdAndStatus_Call{Call: _e.mock.On("GetLoanByUserIdAndStatus", ctx, userId, status)}
}

func (_c *MockStore_GetLoanByUserIdAndStatus_Call) Run(run func(ctx context.Context, userId int, status int)) *MockStore_GetLoanByUserIdAndStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_GetLoanByUserIdAndStatus_Call) Return(loans []psql.Loan, err error) *MockStore_GetLoanByUserIdAndStatus_Call {
	_c.Call.Return(loans, err)
	return _c
}

func (_c *MockStore_GetLoanByUserIdAndStatus_Call) RunAndReturn(run func(ctx context.Context, userId int, status int) ([]psql.Loan, error)) *MockStore_GetLoanByUserIdAndStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetLoanPaymentsByLoanIdsStatusDueDate provides a mock function for the type MockStore
func (_mock *MockStore) GetLoanPaymentsByLoanIdsStatusDueDate(ctx context.Context, loandIds []int, status int, date time.Time, dueDateBeforeDate bool) ([]psql.LoanPayment, error) {
	ret := _mock.Called(ctx, loandIds, status, date, dueDateBeforeDate)

	if len(ret) == 0 {
		panic("no return value specified for GetLoanPaymentsByLoanIdsStatusDueDate")
	}

	var r0 []psql.LoanPayment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int, int, time.Time, bool) ([]psql.LoanPayment, error)); ok {
		return returnFunc(ctx, loandIds, status, date, dueDateBeforeDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int, int, time.Time, bool) []psql.LoanPayment); ok {
		r0 = returnFunc(ctx, loandIds, status, date, dueDateBeforeDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]psql.LoanPayment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int, int, time.Time, bool) error); ok {
		r1 = returnFunc(ctx, loandIds, status, date, dueDateBeforeDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetLoanPaymentsByLoanIdsStatusDueDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoanPaymentsByLoanIdsStatusDueDate'
type MockStore_GetLoanPaymentsByLoanIdsStatusDueDate_Call struct {
	*mock.Call
}

// GetLoanPaymentsByLoanIdsStatusDueDate is a helper method to define mock.On call
//   - ctx context.Context
//   - loandIds []int
//   - status int
//   - date time.Time
//   - dueDateBeforeDate bool
func (_e *MockStore_Expecter) GetLoanPaymentsByLoanIdsStatusDueDate(ctx interface{}, loandIds interface{}, status interface{}, date interface{}, dueDateBeforeDate interface{}) *MockStore_GetLoanPaymentsByLoanIdsStatusDueDate_Call {
	return &MockStore_GetLoanPaymentsByLoanIdsStatusDueDate_Call{Call: _e.mock.On("GetLoanPaymentsByLoanIdsStatusDueDate", ctx, loandIds, status, date, dueDateBeforeDate)}
}

func (_c *MockStore_GetLoanPaymentsByLoanIdsStatusDueDate_Call) Run(run func(ctx context.Context, loandIds []int, status int, date time.Time, dueDateBeforeDate bool)) *MockStore_GetLoanPaymentsByLoanIdsStatusDueDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int
		if args[1] != nil {
			arg1 = args[1].([]int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockStore_GetLoanPaymentsByLoanIdsStatusDueDate_Call) Return(loanPayments []psql.LoanPayment, err error) *MockStore_GetLoanPaymentsByLoanIdsStatusDueDate_Call {
	_c.Call.Return(loanPayments, err)
	return _c
}

func (_c *MockStore_GetLoanPaymentsByLoanIdsStatusDueDate_Call) RunAndReturn(run func(ctx context.Context, loandIds []int, status int, date time.Time, dueDateBeforeDate bool) ([]psql.LoanPayment, error)) *MockStore_GetLoanPaymentsByLoanIdsStatusDueDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockStore
func (_mock *MockStore) GetUser(ctx context.Context, id int) (psql.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 psql.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (psql.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) psql.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(psql.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockStore_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockStore_Expecter) GetUser(ctx interface{}, id interface{}) *MockStore_GetUser_Call {
	return &MockStore_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockStore_GetUser_Call) Run(run func(ctx context.Context, id int)) *MockStore_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetUser_Call) Return(user psql.User, err error) *MockStore_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockStore_GetUser_Call) RunAndReturn(run func(ctx context.Context, id int) (psql.User, error)) *MockStore_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// PayLoan provides a mock function for the type MockStore
func (_mock *MockStore) PayLoan(ctx context.Context, loanId int, loanPaymentIds []int, outstandingDeduction int, OutstandingAmount int) error {
	ret := _mock.Called(ctx, loanId, loanPaymentIds, outstandingDeduction, OutstandingAmount)

	if len(ret) == 0 {
		panic("no return value specified for PayLoan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []int, int, int) error); ok {
		r0 = returnFunc(ctx, loanId, loanPaymentIds, outstandingDeduction, OutstandingAmount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_PayLoan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayLoan'
type MockStore_PayLoan_Call struct {
	*mock.Call
}

// PayLoan is a helper method to define mock.On call
//   - ctx context.Context
//   - loanId int
//   - loanPaymentIds []int
//   - outstandingDeduction int
//   - OutstandingAmount int
func (_e *MockStore_Expecter) PayLoan(ctx interface{}, loanId interface{}, loanPaymentIds interface{}, outstandingDeduction interface{}, OutstandingAmount interface{}) *MockStore_PayLoan_Call {
	return &MockStore_PayLoan_Call{Call: _e.mock.On("PayLoan", ctx, loanId, loanPaymentIds, outstandingDeduction, OutstandingAmount)}
}

func (_c *MockStore_PayLoan_Call) Run(run func(ctx context.Context, loanId int, loanPaymentIds []int, outstandingDeduction int, OutstandingAmount int)) *MockStore_PayLoan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []int
		if args[2] != nil {
			arg2 = args[2].([]int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockStore_PayLoan_Call) Return(err error) *MockStore_PayLoan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_PayLoan_Call) RunAndReturn(run func(ctx context.Context, loanId int, loanPaymentIds []int, outstandingDeduction int, OutstandingAmount int) error) *MockStore_PayLoan_Call {
	_c.Call.Return(run)
	return _c
}
